---
apiVersion: v2
name: external-secrets
description: External Secrets Operator chart wrapper with custom values
type: application
version: 0.1.0
appVersion: "1.2.1"

dependencies:
  - name: external-secrets
    version: "1.2.1"
    repository: "https://charts.external-secrets.io"
