---
# Crossplane Kubernetes Provider values

kubernetes:
  enabled: true
  package: "crossplane/provider-kubernetes:v1.2.0"

# Provider configuration
providerConfig:
  create: true
  name: kubernetes-provider
  credentials:
    source: InjectedIdentity
