{{- if .Values.kubernetes.enabled }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
  labels:
    app.kubernetes.io/name: kubernetes-provider
spec:
  package: {{ .Values.kubernetes.package }}
{{- end }}
