---
apiVersion: v2
name: argocd
description: Argo CD chart wrapper with custom values
type: application
version: 0.1.0
appVersion: "3.2.3"

dependencies:
  - name: argo-cd
    version: "9.2.3"
    repository: "https://argoproj.github.io/argo-helm"
